github known_hosts: Try using run_once before_ script due to chicken-egg issue

diff --git a/.chezmoiscripts/run_once_before_00-bootstrap-github-known_hosts.sh.tmpl b/.chezmoiscripts/run_once_before_00-bootstrap-github-known_hosts.sh.tmpl
--- a/.chezmoiscripts/run_once_before_00-bootstrap-github-known_hosts.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_00-bootstrap-github-known_hosts.sh.tmpl
@@ -1,17 +1,34 @@
-{{- /* chezmoi:modify-template */ -}}
+#!/bin/sh
+# -u bail on unset vars
+# -e bail on pipefail
+set -eu
+
+if [[ -z "${CHEZMOI_WORKING_TREE}" ]]; then
+    echo "Error, \$CHEZMOI_WORKING_TREE must be set. Please only run this script via chezmoi"
+    exit 1
+fi
+{{- /* vim: set ft=gotmpl */ -}}
 {{- /* Only add github.com SSH pubkeys on first bootstrap run */ -}}
-{{- if .chezmoi.stdin -}}
 {{- /* Do not modify pre-existing ~/.ssh/known_hosts */ -}}
-{{-   .chezmoi.stdin }}
-{{- else -}}
+{{- $sshDir := joinPath .chezmoi.destDir ".ssh" -}}
+{{- $sshKnownHosts := joinPath $sshDir "known_hosts.modify_test" -}}
+if [ ! -e "{{ $sshKnownHosts }}" ]; then
+  if [ ! -d "{{ $sshDir }}" ] ; then
+    mkdir -p "{{ $sshDir }}"
+    chmod 0700 "{{ $sshDir }}"
+  fi
+  cat >>{{ $sshKnownHosts }}<<-EOKH
 {{-   if stat (joinPath .chezmoi.cacheDir "github-meta-api") -}}
 {{-     $gitKeys := get (include (joinPath .chezmoi.cacheDir "github-meta-api") | fromJson) "ssh_keys" -}}
 {{      range $gitKeys }}github.com {{ . }}
 {{      end -}}
 {{-   else -}}
 {{- /* If API metadata was unavailable, use latest static keys as of 2025-07-03 */ -}}
+# Static
 github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
 github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
 github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
 {{    end -}}
-{{  end -}}
+EOKH
+
+fi
